variables:
  IMAGE_NAME: gcr.io/tidy-federation-332618/nothink-miniapp:staging
  RUN_ARGS: -p 2004:3000
stages:
  - build-image
  - deploy
  - rollback

build:
  stage: build-image
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=gcloud-service-key.json
    # - echo gcloud-service-key.json | docker login -u _json_key --password-stdin https://gcr.io
    - rm -f .env
    - echo VITE_PUBLIC_NODE_RPC_URL=$VITE_PUBLIC_NODE_RPC_URL >> .env
    - echo VITE_PUBLIC_NODE_FAUCET_URL=$VITE_PUBLIC_NODE_FAUCET_URL >> .env
    - echo VITE_PUBLIC_NODE_API_URL=$VITE_PUBLIC_NODE_API_URL >> .env
    - echo VITE_PUBLIC_API_URL=$VITE_PUBLIC_API_URL >> .env
    - echo VITE_PUBLIC_SOCKET_URL=$VITE_PUBLIC_SOCKET_URL >> .env
    - cat .env
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - master
  tags:
    - staging

deploy:
  variables:
    SERVER_IP: 10.156.0.12
  stage: deploy
  script:
    - chmod og= $STAGING_SSH_KEY
    - echo $GCLOUD_SERVICE_KEY | base64 -d > gcloud-service-key.json
    - scp -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no gcloud-service-key.json staging@$SERVER_IP:/tmp/gcloud-service-key.json

    - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@$SERVER_IP "cat /tmp/gcloud-service-key.json | docker login -u _json_key --password-stdin https://gcr.io"
    # - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@10.156.0.10 "gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json"
    # - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@10.156.0.10 "rm keys.json"
    - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@$SERVER_IP "docker stop nothink-miniapp-staging || true"
    - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@$SERVER_IP "docker rm nothink-miniapp-staging || true"
    - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@$SERVER_IP "docker pull ${IMAGE_NAME}"
    - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@$SERVER_IP "docker run -d ${RUN_ARGS} --name nothink-miniapp-staging ${IMAGE_NAME}"
    # Тут может быть скрипт для SSH и запуска Docker контейнера на целевом сервере
  only:
    - master
  tags:
    - staging

deploy_production:
  variables:
    SERVER_IP: 10.156.0.12
    RUN_ARGS: -p 2004:3000
  stage: deploy
  script:
    - chmod og= $PRODUCTION_SSH_KEY
    - echo $GCLOUD_SERVICE_KEY | base64 -d > gcloud-service-key.json
    - scp -i $PRODUCTION_SSH_KEY -o StrictHostKeyChecking=no gcloud-service-key.json production@$SERVER_IP:/tmp/gcloud-service-key.json

    - ssh -i $PRODUCTION_SSH_KEY -o StrictHostKeyChecking=no production@$SERVER_IP "cat /tmp/gcloud-service-key.json | docker login -u _json_key --password-stdin https://gcr.io"
    # - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@10.156.0.10 "gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json"
    # - ssh -i $STAGING_SSH_KEY -o StrictHostKeyChecking=no staging@10.156.0.10 "rm keys.json"
    - ssh -i $PRODUCTION_SSH_KEY -o StrictHostKeyChecking=no production@$SERVER_IP "docker stop nothink-miniapp-production || true"
    - ssh -i $PRODUCTION_SSH_KEY -o StrictHostKeyChecking=no production@$SERVER_IP "docker rm nothink-miniapp-production || true"
    - ssh -i $PRODUCTION_SSH_KEY -o StrictHostKeyChecking=no production@$SERVER_IP "docker pull ${IMAGE_NAME}"
    - ssh -i $PRODUCTION_SSH_KEY -o StrictHostKeyChecking=no production@$SERVER_IP "docker run -d ${RUN_ARGS} --name nothink-miniapp-production ${IMAGE_NAME}"
    # Тут может быть скрипт для SSH и запуска Docker контейнера на целевом сервере
  only:
    - master
  when: manual
  tags:
    - staging
